return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.8.6",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 169,
  height = 113,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 53,
  nextobjectid = 1791,
  properties = {},
  tilesets = {
    {
      name = "images",
      firstgid = 1,
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "refs",
      firstgid = 1,
      tilewidth = 194,
      tileheight = 193,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {
        {
          id = 0,
          image = "refs/Ch08_Body_0004.png",
          width = 194,
          height = 193
        },
        {
          id = 1,
          image = "refs/Ch08_Body_0005.png",
          width = 44,
          height = 193
        }
      }
    },
    {
      name = "pexel",
      firstgid = 3,
      tilewidth = 5403,
      tileheight = 3602,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 1,
      tiles = {
        {
          id = 1,
          image = "../../../../../../../../../../Z_DATAS/GFX/pexels/abstract/pexels-steve-johnson-1698394.jpg",
          width = 5403,
          height = 3602
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 47,
      name = "pexel",
      visible = true,
      opacity = 0.44,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 85, 255 },
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 20,
      name = "PARTICLES",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 10,
          name = "particles_bg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 11,
          name = "particles_mg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 12,
          name = "particles_fg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 27,
      name = "LIGHTINGS",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 29,
          name = "lightings",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 25,
      name = "SHADOWS",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 26,
          name = "shadows",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 6,
      name = "IMAGES_DECO_BG",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 15,
          name = "bg2_deco_backB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 16,
          name = "bg2_deco_backA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 7,
          name = "bg2_deco_base",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 17,
          name = "bg2_deco_frontA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 30,
          name = "bg2_deco_frontB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 18,
          name = "bg1_deco_backB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 35,
          name = "bg1_deco_backA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 34,
          name = "bg1_deco_base",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 33,
          name = "bg1_deco_frontA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 31,
          name = "bg1_deco_frontB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 36,
      name = "IMAGES_DECO_FG",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 41,
          name = "fg1_deco_backB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 40,
          name = "fg1_deco_backA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 39,
          name = "fg1_deco_base",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 38,
          name = "fg1_deco_frontA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 37,
          name = "fg1_deco_frontB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 19,
      name = "ACTORS",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 21,
          name = "actors_bg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 538,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 760,
              y = 3280,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 544,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 856,
              y = 3280,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 545,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1080,
              y = 3280,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 546,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1176,
              y = 3280,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 547,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 968,
              y = 3280,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 548,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1120,
              y = 3264,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 549,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1216,
              y = 3264,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 550,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1440,
              y = 3264,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 551,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1472,
              y = 3184,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 552,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1328,
              y = 3264,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 553,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1536,
              y = 3160,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 554,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1632,
              y = 3160,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 555,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1816,
              y = 3232,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 556,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2104,
              y = 3200,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 557,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1744,
              y = 3184,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 558,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1888,
              y = 3312,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 559,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 1976,
              y = 3336,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 560,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2176,
              y = 3352,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 561,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2272,
              y = 3352,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 562,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2064,
              y = 3352,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 563,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2424,
              y = 3248,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 564,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2496,
              y = 3400,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 565,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2720,
              y = 3400,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 566,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2816,
              y = 3400,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 567,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2608,
              y = 3400,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 568,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2768,
              y = 3344,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 569,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2928,
              y = 3416,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 570,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3152,
              y = 3416,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 571,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3248,
              y = 3416,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 572,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3040,
              y = 3416,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 573,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2880,
              y = 3224,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 574,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 2976,
              y = 3224,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 575,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3200,
              y = 3224,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 576,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3296,
              y = 3224,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 577,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3088,
              y = 3224,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 578,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3344,
              y = 3440,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 579,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3440,
              y = 3440,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 580,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3664,
              y = 3440,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 581,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3760,
              y = 3440,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 582,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 3552,
              y = 3440,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 583,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 472,
              y = 3472,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 613,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 504,
              y = 3312,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 614,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 472,
              y = 3440,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 615,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 472,
              y = 3408,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 616,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 472,
              y = 3376,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 617,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 472,
              y = 3344,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 618,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 536,
              y = 3312,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 619,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 472,
              y = 3312,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 622,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 568,
              y = 3280,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 623,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 600,
              y = 3248,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 624,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 632,
              y = 3216,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 625,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 664,
              y = 3248,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 626,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 696,
              y = 3280,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 627,
              name = "coinA",
              type = "",
              shape = "polygon",
              x = 728,
              y = 3312,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 0 },
                { x = 0, y = -16 },
                { x = -16, y = 0 },
                { x = 0, y = 16 },
                { x = 16, y = 0 }
              },
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 9,
          name = "actors_mg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 5,
              name = "player1",
              type = "",
              shape = "polygon",
              x = 128,
              y = 3168,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -48 },
                { x = -32, y = 0 },
                { x = 0, y = 48 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 28,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 2048,
              y = 3056,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 232,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 912,
              y = 3288,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 628,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 2832,
              y = 3144,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 629,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 2640,
              y = 3128,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 630,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 2992,
              y = 3304,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 631,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 3136,
              y = 3128,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 632,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 4000,
              y = 3264,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 633,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 3584,
              y = 3208,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 634,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 3744,
              y = 3168,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 635,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 5040,
              y = 3296,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 636,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 4800,
              y = 3312,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 637,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 4576,
              y = 3312,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 638,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 4352,
              y = 3288,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 639,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 3424,
              y = 3328,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 640,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 3264,
              y = 3200,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 647,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 4160,
              y = 3256,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 682,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 5104,
              y = 3200,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 683,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 4864,
              y = 3216,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            },
            {
              id = 684,
              name = "nmeA",
              type = "",
              shape = "polygon",
              x = 4640,
              y = 3216,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 32, y = 0 },
                { x = 0, y = -32 },
                { x = -32, y = 0 },
                { x = 0, y = 32 },
                { x = 32, y = 0 }
              },
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 22,
          name = "actors_fg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 23,
      name = "SHAPES_DECO",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 2,
          name = "shapes_bg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1627,
              name = "",
              type = "",
              shape = "polygon",
              x = 3560,
              y = 2936,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = -216, y = 40 },
                { x = -240, y = 344 },
                { x = 16, y = 376 },
                { x = 43.2941, y = 253.176 },
                { x = 48, y = 200 },
                { x = 0, y = 184 },
                { x = -40, y = 184 },
                { x = -48, y = 216 },
                { x = -8, y = 224 },
                { x = -32, y = 296 },
                { x = -176, y = 264 },
                { x = -168, y = 88 },
                { x = 24, y = 56 }
              },
              properties = {}
            },
            {
              id = 1628,
              name = "",
              type = "",
              shape = "polygon",
              x = 3688,
              y = 3088,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 16, y = 208 },
                { x = 64, y = 192 },
                { x = 56, y = -16 }
              },
              properties = {}
            },
            {
              id = 1629,
              name = "",
              type = "",
              shape = "polygon",
              x = 3688,
              y = 3008,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = 0, y = -64 },
                { x = 48, y = -64 },
                { x = 48, y = 0 }
              },
              properties = {}
            },
            {
              id = 1630,
              name = "",
              type = "",
              shape = "polygon",
              x = 3848,
              y = 2984,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = -8, y = 304 },
                { x = 128, y = 304 },
                { x = 176, y = 264 },
                { x = 176, y = 64 },
                { x = 104, y = 0 },
                { x = 16, y = 0 },
                { x = 16, y = 48 },
                { x = 96, y = 56 },
                { x = 128, y = 120 },
                { x = 128, y = 240 },
                { x = 96, y = 272 },
                { x = 16, y = 264 },
                { x = 16, y = 0 }
              },
              properties = {}
            },
            {
              id = 1631,
              name = "",
              type = "",
              shape = "polygon",
              x = 4104,
              y = 3024,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = -16, y = 248 },
                { x = 160, y = 256 },
                { x = 160, y = 200 },
                { x = 40, y = 200 },
                { x = 40, y = 152 },
                { x = 80, y = 152 },
                { x = 80, y = 112 },
                { x = 32, y = 104 },
                { x = 32, y = 24 },
                { x = 144, y = 8 },
                { x = 128, y = -48 }
              },
              properties = {}
            },
            {
              id = 1632,
              name = "",
              type = "",
              shape = "polygon",
              x = 4320,
              y = 3272,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = -8, y = -296 },
                { x = 168, y = -304 },
                { x = 192, y = -240 },
                { x = 184, y = -152 },
                { x = 48, y = -152 },
                { x = 48, y = -184 },
                { x = 144, y = -184 },
                { x = 152, y = -232 },
                { x = 128, y = -272 },
                { x = 32, y = -264 },
                { x = 48, y = -184 },
                { x = 48, y = -152 },
                { x = 88, y = -152 },
                { x = 144, y = -96 },
                { x = 176, y = -48 },
                { x = 200, y = -8 },
                { x = 152, y = 8 },
                { x = 120, y = -56 },
                { x = 48, y = -152 },
                { x = 48, y = -8 }
              },
              properties = {}
            },
            {
              id = 1633,
              name = "",
              type = "",
              shape = "polygon",
              x = 4592,
              y = 3024,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = -40, y = 232 },
                { x = 120, y = 232 },
                { x = 160, y = -56 },
                { x = 8, y = 0 },
                { x = 8, y = 56 },
                { x = 112, y = 8 },
                { x = 128, y = 8 },
                { x = 120, y = 56 },
                { x = 88, y = 200 },
                { x = 0, y = 192 },
                { x = 8, y = 56 },
                { x = 8, y = 0 }
              },
              properties = {}
            },
            {
              id = 1634,
              name = "",
              type = "",
              shape = "polygon",
              x = 4976,
              y = 3000,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              polygon = {
                { x = 0, y = 0 },
                { x = -64, y = -8 },
                { x = -120, y = 0 },
                { x = -128, y = 96 },
                { x = -8, y = 136 },
                { x = -8, y = 232 },
                { x = -160, y = 272 },
                { x = -168, y = 224 },
                { x = -64, y = 192 },
                { x = -64, y = 144 },
                { x = -120, y = 136 },
                { x = -160, y = 104 },
                { x = -152, y = -24 },
                { x = 0, y = -24 }
              },
              properties = {}
            },
            {
              id = 1783,
              name = "",
              type = "",
              shape = "rectangle",
              x = 920,
              y = 3512,
              width = 64,
              height = 8,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1785,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1552,
              y = 3232,
              width = 64,
              height = 8,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1786,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2288,
              y = 3504,
              width = 64,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1787,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2392,
              y = 2848,
              width = 72,
              height = 672,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 4,
          name = "shapes_fg",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 24,
      name = "SHAPES_PHYSICS",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 50,
          name = "springs",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 512,
              name = "",
              type = "",
              shape = "rectangle",
              x = 928,
              y = 3520,
              width = 48,
              height = 8,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 522,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1560,
              y = 3240,
              width = 48,
              height = 8,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 530,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2296,
              y = 3520,
              width = 48,
              height = 8,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 51,
          name = "mvplatforms",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 523,
              name = "x1024",
              type = "",
              shape = "rectangle",
              x = 736,
              y = 3248,
              width = 128,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 526,
              name = "y100",
              type = "",
              shape = "rectangle",
              x = 2880,
              y = 3368,
              width = 240,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 528,
              name = "x304y248",
              type = "",
              shape = "rectangle",
              x = 2552,
              y = 3296,
              width = 264,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1643,
              name = "x2072",
              type = "",
              shape = "rectangle",
              x = 3200,
              y = 3280,
              width = 128,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 49,
          name = "ptplatforms",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 506,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2016,
              y = 3424,
              width = 192,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 516,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2016,
              y = 3264,
              width = 192,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 518,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2016,
              y = 3104,
              width = 192,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 521,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2016,
              y = 2944,
              width = 192,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1645,
              name = "",
              type = "",
              shape = "rectangle",
              x = 3200,
              y = 3368,
              width = 640,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1646,
              name = "",
              type = "",
              shape = "rectangle",
              x = 3936,
              y = 3376,
              width = 640,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1647,
              name = "",
              type = "",
              shape = "rectangle",
              x = 4672,
              y = 3376,
              width = 600,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1779,
              name = "",
              type = "",
              shape = "rectangle",
              x = 3096,
              y = 3216,
              width = 216,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1789,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2360,
              y = 2832,
              width = 136,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 48,
          name = "ladders",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 507,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2400,
              y = 2856,
              width = 56,
              height = 568,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 52,
          name = "walls",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 3,
          name = "floor",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 403,
              name = "trp",
              type = "",
              shape = "rectangle",
              x = -32,
              y = 0,
              width = 64,
              height = 3616,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 461,
              name = "",
              type = "",
              shape = "rectangle",
              x = 32,
              y = 3520,
              width = 5344,
              height = 96,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 529,
              name = "trp",
              type = "",
              shape = "rectangle",
              x = 5376,
              y = 0,
              width = 64,
              height = 3616,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 531,
              name = "",
              type = "",
              shape = "rectangle",
              x = 552,
              y = 3360,
              width = 224,
              height = 160,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 533,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1248,
              y = 3360,
              width = 224,
              height = 160,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 535,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1472,
              y = 3240,
              width = 224,
              height = 280,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 536,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1696,
              y = 3360,
              width = 224,
              height = 160,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 537,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1696,
              y = 3296,
              width = 64,
              height = 64,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1780,
              name = "",
              type = "",
              shape = "rectangle",
              x = 3320,
              y = 3136,
              width = 1840,
              height = 40,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1781,
              name = "",
              type = "",
              shape = "rectangle",
              x = 224,
              y = 3392,
              width = 192,
              height = 128,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1784,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1024,
              y = 3264,
              width = 80,
              height = 256,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "refs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 412,
          name = "jumpheight",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 3360,
          width = 64,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "jumpheight",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 3344,
          width = 512,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1644,
          name = "jumpheight",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 3296,
          width = 2072,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
